<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Only Wallz</title>
    <link rel="stylesheet" type="text/css" href="css/main.min.css">
</head>
<body>
<div id="wall" style="background-image: url('<?php echo $wallpaper ?>');">
<div id="newwall" class="raisedbutton"><span>Reload</span></div>
<div id="wallsubmit">
    <div id="showsubmit" class="raisedbutton"><span>Create a Wall</span></div>
    <div id="submitform" style="display:none;">
    <input class="audio" type="text" value="" placeholder="Youtube link...">
    <input class="wallpaper" type="text" value="" placeholder="Wallpaper url...">
    <div id="submit" class="raisedbutton"><span>Submit</span></div>
        </div>

</div>

    <div class="middiv"><div id="videocontainer"></div></div>
</div>
</body>
<script async src="js/lib/resources.min.js"></script>
<script async src="js/app.js"></script>
</html>