<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Only Wallz</title>
</head>
<body>
<div id="wall">
<div id="newwall" class="raisedbutton"><span>Reload</span></div>
<div id="wallsubmit">
    <div id="showsubmit" class="raisedbutton"><span>Create a Wall</span></div>
    <div id="submitform" style="display:none;">
    <input class="audio" type="text" value="" placeholder="Youtube link...">
    <input class="wallpaper" type="text" value="" placeholder="Wallpaper url...">
    <div id="submit" class="raisedbutton"><span>Submit</span></div>
        </div>

</div>

    <div class="middiv"><div id="videocontainer"></div></div>
</div>
</body>
<link rel="stylesheet" type="text/css" href="css/main.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="js/lib/underscore-min.js"></script>
<script src="js/lib/backbone-min.js"></script>
<script src="js/Models/WallModel.js"></script>
<script src="js/Views/WallView.js"></script>
<script src="js/load.js"></script>
</html>