<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Only Wallz</title>
</head>
<body>
<div id="wall">
<div id="newwall" class="raisedbutton"><span>Reload</span></div>
</div>
</body>
<link rel="stylesheet" type="text/css" href="css/main.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="js/lib/underscore-min.js"></script>
<script src="js/lib/backbone-min.js"></script>
<script src="js/Models/WallModel.js"></script>
<script src="js/Views/WallView.js"></script>
<script src="js/load.js"></script>
</html>